import React, { useState, useEffect } from 'react';
import * as ReactDOM from 'react-dom';
import { Game } from './ui/game';
import { Lobby } from './ui/lobby';

declare global {
  interface Window {
    selectedGameID: string;
    autogeneratedGameID: string;
  }
}

function App() {
  const [gameID, setGameID] = useState(null);

  useEffect(() => {
    if (document.location.hash) {
      setGameID(document.location.hash.slice(1));
    }
    if (window.selectedGameID) {
      setGameID(window.selectedGameID);
    }
  });

  return (
    <div id="application">
      <div id="topbar">
        <h1>
          <a href={'http://' + window.location.host}>Codenames</a>
        </h1>
      </div>
      {gameID ? (
        <Game gameID={gameID} />
      ) : (
        <Lobby defaultGameID={window.autogeneratedGameID} />
      )}
    </div>
  );
}

document.addEventListener('DOMContentLoaded', (event) => {
  ReactDOM.render(<App />, document.getElementById('app'));
});
